Name: Linting and Testing

on:
  Push:
    Branches:
      - master
  pull_request:

Jobs:
  linting:
    Name: Run Linters
    runs-on: ubuntu-latest

    Steps:
      - Name: Checkout code
        Uses: actions/checkout@v4
                  
      - Uses: pnpm/action-setup@v2
        with:
          version: 8

      - Name: Install Node.js
        Uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      
      - Name: install packages
        run: pnpm i
      
      - Name: Run ESLint
        run: pnpm run lint

  Building:
    Name: Build project
    runs-on: ubuntu-latest

    Steps:
      - Name: Checkout code
        Uses: actions/checkout@v4
                  
      - Uses: pnpm/action-setup@v2
        with:
          version: 8

      - Name: Install Node.js
        Uses: actions/setup-node@v4
        with:
          node-version: 20
          Cache: 'pnpm'
      
      - Name: install packages
        run: pnpm install

      - Name: Build project
        run: pnpm build

  docker:
    Name: Build docker
    runs-on: ubuntu-latest

    Steps:
      - Name: Checkout code
        Uses: actions/checkout@v4
      
      - Name: Set up Docker Buildx
        Uses: docker/setup-buildx-action@v3

      - Name: build
        Uses: docker/build-push-action@v5
